### ISSUE TITLE
Use FOTA library's currentFwVersion 

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/bifravst#203]
The Azure FOTA library has its own version string schema, so this should be used instead of the string in the `dev` object.

```json
"reported": {
      "firmware": {
        "fwUpdateStatus": "current",
        "currentFwVersion": "0.0.0-dev",
        "pendingFwVersion": ""
      }
}
```

**Comment by simensrostad** [comment]
In the "dev" object?

**Comment by coderbyheart** [comment]
Yes:

https://github.com/bifravst/bifravst/blob/9cfa7329df3049875da99b64378b43271ee78b21/docs/firmware/state.schema.json#L209-L214

**Comment by coderbyheart** [comment]
This has been implemented in the documentation, web app and Azure implementation itself.

@simensrostad can you take care of removing the `appV` from the `dev` object for the Azure firmware?

**Comment by simensrostad** [comment]
> This has been implemented in the documentation, web app and Azure implementation itself.
> 
> @simensrostad can you take care of removing the `appV` from the `dev` object for the Azure firmware?

Yes. Entry removed from `azure_iot_hub_codec.c` in the branch that adds azure support. https://github.com/bifravst/firmware/tree/add_nrf_azure_codecs
